### ISSUE TITLE
Localização

### ISSUE THREAD

**Issue by pedroaaraujo** [groupsc10/WBot#1]
Adicionar rotina para identificar latitude e longitude da localização enviada pelo contato.

**Comment by groupsc10** [comment]
Ao monitrar as mensagens pode recuperar as seguintes propriedades, Message.lat & Message.lng, caso o usuario tenha enviado vai estar nessas propriedades um valor diferente de 0.

**Comment by heliosroots** [comment]
O evento OnRequestChat entrega pra vc um objeto Chats(TResponseChat).... é só vc ir seguindo a hierarquia desse objeto q vc vai chegar em Message(TMessage).... nele vc encontra as propriedade lat(latitude) e lng(longitude)....

![image](https://user-images.githubusercontent.com/1609436/96519262-f73c5580-1242-11eb-95ae-d169fa5cf10f.png)



_Não esqueça de um feedback... isso importante para gente continuar a evoluir juntos... obrigado._

**Comment by pedroaaraujo** [comment]
Testado e aprovado.
Obrigado.
